Vagrant.configure("2") do | config |
  config.vm.box = "ubuntu/trusty64"
  config.ssh.forward_agent = true

  config.vm.provision "ansible" do | ansible |
    ansible.playbook = "packer.yml"

    ansible.verbose = "vvvv"
    ansible.extra_vars = {
      ansible_python_interpreter: "/usr/bin/python",
      is_local: "true",
     }
  end

  config.vm.provision "shell", path: "scripts/serverspec.sh"
end
