Vagrant.configure("2") do | config |
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision "ansible" do | ansible |
    ansible.playbook = "packer.yml"
    ansible.extra_vars = {
      ansible_python_interpreter: "/usr/bin/python3",
     }
  end

  config.vm.provision "shell", path: "scripts/serverspec.sh"
end
